# # - if any PR exists with "ci-internal:merge":
# #     skip

# # for-each PR:
# #   if:
# #     - PR checks are all finished and green
# #     - PR has label "ready-for-merge"
# #   then:
# #     if needsRebase:
# #       "ci-internal:rebase"
# #       rebasePr()
# #     else:
# #       "ci-internal:merging"
# #       bumpDeps()
# #       generate3rdPartyLicenses()
# #       commit -m '[ci skip] update deps and licenses'
# #       mergeToMain()
# #       "ci-internal:"

# name: Merge PR into Main

# on:
#   pull_request:
#     types: [labeled]

# env:
#   DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

# jobs:
#   main:
#     if: ${{ github.event.label.name == 'ci-internal:merge' }}
#     name: Merge Main
#     runs-on: ubuntu-latest
#     steps:
#       - name: git checkout
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           ref: ${{ github.event.pull_request.head.ref }}
#           fetch-depth: 0

#       - name: perform merge
#         run: |
#           gh pr merge "$PR_NUMBER" \
#             --squash \
#             --delete-branch \
#             --subject 'merge PR "$PR_NUMBER"'
#         env:
#           PR_NUMBER: ${{github.event.number}}

#       - name: remove label
#         if: always()
#         uses: actions-ecosystem/action-remove-labels@v1
#         with:
#           labels: ci-internal:merge