name: Merge Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  main:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.label.name == 'ci-internal:merge' }}
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          # fetch the entire history
          # this is necessary for tasks that needs
          # the real git history (ie. reading git log, committing back changes)
          fetch-depth: 0
          # don't checkout a detatched HEAD
          ref: ${{ github.head_ref }}

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ^14.17.5
          cache: 'npm'

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: |
          npm ci

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump packages
        run: |
          node scripts/bump-version.js
          git add .
          git commit --no-allow-empty -m "chore: bump dependencies" || true

      - name: Push
        env:
          PR_HEAD_REF: ${{github.head_ref}}
        run: |
          git push --set-upstream origin ${PR_HEAD_REF}

      - name: Merge PR
        env:
          PULL_REQUEST_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          gh pr merge $PULL_REQUEST_NUMBER --squash --delete-branch

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-internal:merge

      - name: remove label
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-internal:merge-failed

      - name: add label on failure
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ci-internal:merge-failed
