name: Rebase Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  main:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.label.name == 'ci-internal:rebase' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          # otherwise, there would be errors pushing refs to the destination repository
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # we need to use a PAT so checks gets re-run
          # see: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          token: ${{ secrets.PAT }}

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Rebase
        env:
          PR_BASE_REF: ${{github.base_ref}}
        run: |
          git rebase origin/${PR_BASE_REF}

      - name: Push
        env:
          PR_HEAD_REF: ${{github.head_ref}}
        run: |
          git push --set-upstream origin ${PR_HEAD_REF} --force-with-lease

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-internal:rebase

      - name: remove label
        if: success()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-internal:rebase-failed

      - name: add label on failure
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ci-internal:rebase-failed
