name: Mark Pull Requests for rebase

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Mark PRs for Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.head_ref }}

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Label all open prs for rebase
        env:
          # we need to use a PAT so checks gets re-run
          # see: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr list --state open --json url | \
            jq -r .[].url | \
            while read line ; do \
              gh pr edit $line --add-label ci-internal:rebase ; \
              done
