# This action runs lint checks and tests against the code.
name: Check and Test

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  check-and-test:
    name: Check and Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Say hi
        run: |
          echo 'hi!'
        shell: bash
