# name: Publish
# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main
#
# jobs:
#   publish:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: "Checkout"
#       uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#
#     - name: "Use NodeJS 14"
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#
#     - name: "Publish what is not already in NPM"
#       env:
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#       run: |
#         npx lerna publish --no-git-tag-version --no-push from-package --yes
