# Release Notes are meant to be
# displayed to users as part of the
# auto-update process.
#
# The following workflow:
# - removes the "by @username" and PR info
# - removes the contributors section
# - turn COMPASS-* and MONGOSH-* into links
#
name: Release Notes - Cleanup
on:
  release:
    types: [created, edited]

jobs:
  cleanup_notes:
    name: Cleanup Notes
    runs-on: ubuntu-latest
    steps:
      - name: "Clean up notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat $GITHUB_EVENT_PATH | \
            jq -r .release.body | \
            sed 's/ by @.*//' | \
            grep -v 'New Contributors' | \
            grep -v '* @' | \
            grep -v '<!--' | \
            sed 's/COMPASS-[0-9]\{1,5\}/[&](https:\/\/jira.mongodb.org\/browse\/&)/g' | \
            sed 's/MONGOSH-[0-9]\{1,5\}/[&](https:\/\/jira.mongodb.org\/browse\/&)/g' \
            > RELEASE_NOTES.md

          RELEASE_TAG=$(cat ${GITHUB_EVENT_PATH} | jq -r .release.tag_name)
          gh release edit ${RELEASE_TAG} --notes-file RELEASE_NOTES.md
