name: Release Notes - Cleanup Notes
on:
  release:
    types: [created, edited, published]

jobs:
  cleanup_notes:
    name: Cleanup Notes
    runs-on: ubuntu-latest
    steps:
      - name: "Clean up notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat $GITHUB_EVENT_PATH | jq
